#ifndef DEBUG_H
#define DEBUG_H

#define DEBUG_ORBIT 0
#define DEBUG_COMPASS 1
#define DEBUG_TSOPS 0
#define DEBUG_LIGHT 0

#define DEBUG_MANUAL 0

#define DEBUG_ANY DEBUG_ORBIT || DEBUG_COMPASS || DEBUG_LIGHT || DEBUG_TSOPS || DEBUG_MANUAL

#endif
