#ifndef DEBUG_H
#define DEBUG_H

#define DEBUG_ORBIT 0
#define DEBUG_COMPASS 0
#define DEBUG_TSOPS 0
#define DEBUG_LIGHT 0
#define DEBUG_CAMERA_RAW 0

#define DEBUG_ANY DEBUG_ORBIT || DEBUG_COMPASS || DEBUG_LIGHT || DEBUG_TSOPS || DEBUG_CAMERA_RAW

#endif
